# Generated by Django 5.0.7 on 2024-07-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_accounts', '0002_address_designation_role_userprofile_useraddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
