# Generated by Django 5.0.7 on 2024-07-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_accounts', '0003_blacklistedtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pic_location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
